---
clusterInfo:
  fqdn: ""
  environment: ""
  class: ""
  subclass: ""
  clusterFQDN: ""
  facility: ""
ingress:
  enabled: true
  clusterURI:
    enabled: true
    subdomain: sigstack
  components:
    - subdomain: rekor
      service:
        name: sigstack-rekor-server
        portName: 3000-tcp
    - subdomain: fulcio
      service:
        name: sigstack-fulcio-server
        portName: http
    - subdomain: dex
      service:
        name: sigstack-dex
        portName: http
  domains: []

rekor:
  enabled: true 
  server:
    ingress:
      enabled: false
    logging:
      production: true

  trillian:
    forceNamespace: "sigstack"
    namespace:
      name: "sigstack"
      create: false
    mysql:
      auth:
        existingSecret: sigstack-db-secrets

fulcio:
  forceNamespace: "sigstack"
  enabled: true 
  namespace:
    create: false
    name: sigstack
  server:
    ingress:
      http:
        enabled: false
      grpc:
        enabled: false

  ctlog:
    namespace:
      name: "sigstack"
      create: false
    forceNamespace: "sigstack"
    createctconfig:
      fulcioURL: "http://sigstack-fulcio-server.sigstack.svc" 
    trillian:
      namespace: "sigstack"

dex:
  enabled: true
  configSecret:
    create: false
    name: sigstack-dex-config
