---
clusterInfo:
  environment: prod
  class: core
  subclass: primary
  clusterFQDN: "core-primary-a.ny5.metalkube.net"
  facility: "ny5"
ingress:
  enabled: true
  clusterURI:
    enabled: true
    subdomain: sigstack
  components:
    - subdomain: rekor
      service:
        name: sigstack-rekor-server
        portName: 3000-tcp
    - subdomain: fulcio
      service:
        name: sigstack-fulcio-server
        portName: http
    - subdomain: dex
      service:
        name: sigstack-dex
        portName: http
  domains: []

rekor:
  enabled: true 
  server:
    ingress:
      enabled: false
    logging:
      production: true

  trillian:
    forceNamespace: "sigstack"
    namespace:
      name: "sigstack"
      create: false
    mysql:
      auth:
        existingSecret: sigstack-db-secrets

fulcio:
  forceNamespace: "sigstack"
  enabled: true 
  namespace:
    create: false
    name: sigstack
  config:
    contents:
      OIDCIssuers:
        "https://dex.sigstack.core-primary-a.ny5.metalkube.net/auth":
          ClientID: "sigstore"
          Type: "email"
          IssuerURL: "https://dex.sigstack.core-primary-a.ny5.metalkube.net/auth"
        "https://token.actions.githubusercontent.com":
          IssuerURL: "https://token.actions.githubusercontent.com"
          ClientID: "sigstore"
          Type: "github-workflow"
  server:
    ingress:
      http:
        enabled: false
      grpc:
        enabled: false

  ctlog:
    namespace:
      name: "sigstack"
      create: false
    forceNamespace: "sigstack"
    createctconfig:
      fulcioURL: "http://sigstack-fulcio-server.sigstack.svc" 
    trillian:
      namespace: "sigstack"

dex:
  enabled: true
  configSecret:
    create: false
    name: sigstack-dex-config
  envVars:
  - name: LDAP_BINDPW
    valueFrom:
      secretKeyRef:
        key: ldap-bindpw
        name: jumpcloud

# TODO: Rename this to sigstack
rekorDB:
  secrets:
    - name: db-secrets
      espullData:
        - name: mysql-root-password
          key: mysql-root-password
          version: v1
        - name: mysql-password
          key: mysql-password
          version: v1
        - name: mysql-user
          key: mysql-user
          version: v1
        - name: mysql-database
          key: mysql-database
          version: v1
    - name: dex-config
      espullData:
        - name: config.yaml
          key: dex-config
          version: v1
