---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-tls
  namespace: default
spec:
  commonName: registry.default.svc
  dnsNames:
    - registry.default.svc
  usages:
    - digital signature
    - key encipherment
    - server auth
  secretName: registry-tls
  issuerRef:
    group: cert-manager.io
    name: selfsigned-issuer
    kind: ClusterIssuer