{{- if .Values.ingress.enabled }}
{{ $hosts := .Values.ingress.domains }}
{{ $clusterURI := (printf "%s.%s" .Values.ingress.clusterURI.subdomain .Values.clusterInfo.fqdn ) }}
{{ $components := .Values.ingress.components }}
{{ if .Values.ingress.clusterURI.enabled }}
{{ $hosts = (prepend .Values.ingress.domains $clusterURI) }}
{{ end }}
---
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    argocd.argoproj.io/sync-wave: "20"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Facility: {{ .Values.clusterInfo.facility }}";
  name: {{ template "app.name" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
    {{- range $host := $hosts }}
    {{- range $component := $components }}
    - host: {{ printf "%s.%s" $component.subdomain $host }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name:  {{ $component.service.name }}
                port:
                  name: {{ $component.service.portName }}
    {{- end }}
    {{- end }}
  tls:
    {{- range $host := $hosts }}
    {{- range $component := $components }}
    - hosts:
        - {{ printf "%s.%s"  $component.subdomain $host }}
      secretName: {{ $component.subdomain }}-tls
    {{- end }}
    {{- end }}
{{- end }}
