{{- range $secret := .Values.rekorDB.secrets }}
---
apiVersion: keymaker.equinixmetal.com/v1
kind: ExternalSecretPull
metadata:
  name: sigstack-{{ $secret.name }}
  labels:
    k8s-app: sigstack
spec:
  backend: ssm
  mappings:
    {{- range $data := $secret.espullData }}
    - key: /{{ $.Values.clusterInfo.environment }}/{{ $.Release.Namespace }}/{{ $.Values.clusterInfo.facility }}/{{ $.Values.clusterInfo.class }}{{- if ne $.Values.clusterInfo.subclass "" -}}/{{ $.Values.clusterInfo.subclass }}{{- end -}}/{{ $data.key }}/{{ $data.version }}
      name: {{ $data.name }}
    {{- end }}
{{- end }}
---
apiVersion: keymaker.equinixmetal.com/v1
kind: ExternalSecretPull
metadata:
  labels:
    k8s-app: sigstack
  name: jumpcloud
spec:
  backend: ssm
  mappings:
    - key: /prod/sigstack/jumpcloud/v1
      name: ldap-bindpw
