{{- range $secret := .Values.rekorDB.secrets }}
---
apiVersion: keymaker.equinixmetal.com/v1
kind: ExternalSecretPull
metadata:
  name: rekor-{{ $secret.name }}
  labels:
    k8s-app: rekor
spec:
  backend: ssm
  mappings:
    {{- range $data := $secret.espullData }}
    - key: /{{ $.Values.clusterInfo.environment }}/{{ $.Release.Namespace }}/{{ $.Values.clusterInfo.class }}/{{ $data.key }}/{{ $data.version }}
      name: {{ $data.name }}
    {{- end }}
{{- end }}