name: Toolbox Image

on:
  push:
    branches:
      - main

jobs:
  toolbox-image:
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: toolbox
      tag: ${GITHUB_REF_NAME}
      latest: true
      dockerfile_path: images/toolbox/Dockerfile

